void population() {
  button_1_x = displayWidth*1/10;
  button_1_y = displayHeight*3/4;
  button_1_width = displayWidth*1/5;
  button_1_height = displayHeight*1/5;
  button_2_x = displayWidth*7/10;;
  button_2_y = displayHeight*3/4;;
  button_2_width = button_1_width;
  button_2_height = button_1_height;
  rectDisplayX = displayWidth*1/8;
  rectDisplayY = displayHeight*1/8;
  rectDisplayWidth = button_1_width;
  rectDisplayHeight = button_1_width;
  circleX = displayWidth*6/8;
  circleY = displayHeight*1/8;
  circleWidth = displayWidth*1/8;
  circleHeight = displayHeight*1/8;
  anger_x = displayWidth*4/10;
  anger_y = displayHeight*3/4;
  anger_width = displayWidth*1/5;
  anger_height = displayHeight*1/5;
}
